# Generated by Django 2.2.3 on 2020-04-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_auto_20200408_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='description',
            field=models.TextField(default='Здесь будет описание покемона'),
        ),
    ]
